{% set pyproject = load_file_data('pyproject.toml') %}
{% set name = pyproject['project']['name'] %}
{% set home = pyproject['project']['urls']['Homepage'] %}
{% set description = pyproject['project']['description'] %}
{% set license = pyproject['project']['license'] %}

package:
  name: {{ name }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install .

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - setuptools-scm
  run:
    - python >=3.8
    {% for dep in pyproject["project"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pytest
  imports:
    - {{ name }}
  source_files:
    - test/**
  commands:
    - cd test
    - pytest -v --ignore=test_weatherdata.py --ignore=test_dss.py
about:
  home: {{ home }}
  license: {{ license }}
  summary: {{ description }}

