{% set version = "1.0.1"%}

package:
  name: agroservices
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install .

requirements:
  build:
    - python {{PY_VER}}
    - setuptools
  run:
    - python >=3.6
    - appdirs 
    - bs4 
    - pygments 
    - colorlog 
    - requests
    - pyyaml
    - requests_cache
    - jsf

test:
  requires:
    - pytest
  imports:
    - agroservices
  source_files:
    - test/**
  commands:
    - cd test
    - pytest -v --ignore=test_weatherdata.py --ignore=test_dss.py
about:
  home: "https://github.com/openalea/agroservices"
  license: GPL-v3
  summary: "AgroService is a Python package that provides access to IPM Web Services (at least) and a framework to easily implement Web Services wrappers."

