name: agroservices
channels:
  - conda-forge

dependencies:
 - python=3.8
 - appdirs 
 - bs4 
 - pygments 
 - colorlog 
 - requests 
 - requests_cache
 - pytest
 - sphinx_rtd_theme
 - nbsphinx
 - nbsphinx_link