name: agroservices
channels:
  - conda-forge

dependencies:
 - python
 - appdirs 
 - bs4 
 - pygments 
 - colorlog 
 - requests 
 - requests_cache
 - pytest
 - pydata_sphinx_theme
 - sphinx-favicon
 - nbsphinx
 - nbsphinx-link
 - myst-parser
