name: agroservices
channels:
  - conda-forge

dependencies:
  - python=3.8
  - appdirs 
  - bs4 
  - pygments 
  - colorlog 
  - requests 
  - requests_cache
  - pytest
  - sphinx-rtd-theme
  - nbsphinx